ALTER TABLE APEX_EBS.XXDOC_OBJECTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE APEX_EBS.XXDOC_OBJECTS CASCADE CONSTRAINTS;

CREATE TABLE APEX_EBS.XXDOC_OBJECTS
(
  OBJECT_ID            NUMBER                   NOT NULL,
  OBJECT_NAME          VARCHAR2(240 BYTE)       NOT NULL,
  OBJECT_DESCRIPTION   VARCHAR2(2000 BYTE),
  OBJECT_TYPE_ID       NUMBER                   NOT NULL,
  CREATION_DATE        DATE,
  CREATED_BY           VARCHAR2(240 BYTE),
  REQ_PBI_NUMBER       VARCHAR2(240 BYTE),
  REQ_PBI_LINK         VARCHAR2(600 BYTE),
  REQ_PBI_DESCRIPTION  VARCHAR2(2000 BYTE),
  LAST_UPDATED_DATE    DATE,
  LAST_UPDATED_BY      VARCHAR2(240 BYTE),
  STATUS               VARCHAR2(60 BYTE)
)
TABLESPACE APEX_EBS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX APEX_EBS.XXDOC_OBJECTS_PK ON APEX_EBS.XXDOC_OBJECTS
(OBJECT_ID)
LOGGING
TABLESPACE APEX_EBS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER APEX_EBS."XXDOC_OBJECTS_TRG1"
  before insert on "XXDOC_OBJECTS"
  for each row
begin
  if :NEW."OBJECT_ID" is null then
    select "XXDOC_OBJECTS_S".nextval into :NEW."OBJECT_ID" from dual;
  end if;
end;
/


CREATE OR REPLACE TRIGGER APEX_EBS.xxdoc_objects_trg2
   BEFORE UPDATE
   ON APEX_EBS.XXDOC_OBJECTS    FOR EACH ROW
BEGIN
   :NEW.created_by       := :OLD.created_by;
   :NEW.creation_date    := :OLD.creation_date;
END;
/


ALTER TABLE APEX_EBS.XXDOC_OBJECTS ADD (
  CONSTRAINT XXDOC_OBJECTS_CK1
 CHECK (STATUS IN ('INSERVICE','TOBERETIRED','RETIRED')),
  CONSTRAINT XXDOC_OBJECTS_PK
 PRIMARY KEY
 (OBJECT_ID)
    USING INDEX 
    TABLESPACE APEX_EBS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE APEX_EBS.XXDOC_OBJECTS ADD (
  CONSTRAINT XXDOC_OBJECTS_FK1 
 FOREIGN KEY (OBJECT_TYPE_ID) 
 REFERENCES APEX_EBS.XXDOC_OBJECT_TYPES (OBJECT_TYPE_ID));

